- name: Creating environmental variables
  file:
    path: ../microservices/query-builder/.env
    state: touch
    mode: u+rw,g+rw,o+rw
  tags: [ install, update ]

    
- name: Loading required data inside .env file (public installation)
  blockinfile:
    path: ../microservices/query-builder/.env
    block: |
      JWT_SECRET= 'cqube_secret'
      DB_HOST = 'postgres_app'
      DB_PORT = 5432
      DB_USERNAME = "{{ read_only_db_user }}"
      DB_PASSWORD = "{{ read_only_db_password }}"
      DB_NAME = "{{ db_name }}"
      PORT= 3002
      STORAGE_TYPE= "{{ storage_type }}"
      AWS_ACCESS_KEY = "{{ aws_access_key }}"
      AWS_SECRET_KEY = "{{ aws_secret_key }}"
      S3_BUCKET= "{{ s3_bucket }}"
      AWS_BUCKET_REGION= 'ap-south-1'
      MINIO_END_POINT = "{{ minio_ip_address }}"
      MINIO_PORT = 9000
      MINIO_ACCESS_KEY = "{{ minio_username }}"
      MINIO_SECRET_KEY = "{{ minio_password }}"
      MINIO_BUCKET = "{{ minio_bucket }}"
      AZURE_CONNECTION_STRING = "{{ azure_connection_string }}"
      AZURE_CONTAINER = "{{ azure_container }}"
      CONTAINER_FOLDER_NAME = 'process_input'
      ORACLE_BUCKET = "{{ oracle_bucket }}"
      KEY_CLOCK_URL = 'http://keycloak_app:8080/auth'
      REALM = 'cQube'
      KEY_CLOAK_CLIENT_ID = 'cqube-5.0'
      KEY_CLOAK_SECRET = 'd0b8122f-8dfb-46h7-b69a-f5cc4e25d000'
      KEY_CLOAK_ADMIN_CLIENT_ID = 'keycloak-admin'
      KEY_CLOAK_ADMIN_CLIENT_SECRET = '4c19653b-4047-4b19-819a-69315c491763'
      KEY_CLOAK_ADMIN_USERNAME = '{{ keycloak_adm_name }}'
      KEY_CLOAK_ADMIN_PASSWORD = '{{ keycloak_adm_password }}'
  when: mode_of_installation != "localhost"   
  tags: [ install, update ]


- name: Loading required data inside .env file (local installation)
  blockinfile:
    path: ../microservices/query-builder/.env
    block: |
      JWT_SECRET= 'cqube_secret'
      DB_HOST = 'postgres_app'
      DB_PORT = 5432
      DB_USERNAME = "{{ read_only_db_user }}"
      DB_PASSWORD = "{{ read_only_db_password }}"
      DB_NAME = "{{ db_name }}"
      PORT= 3002
      STORAGE_TYPE= "{{ storage_type }}"
      AWS_ACCESS_KEY = "{{ aws_access_key }}"
      AWS_SECRET_KEY = "{{ aws_secret_key }}"
      S3_BUCKET= "{{ s3_bucket }}"
      AWS_BUCKET_REGION= 'ap-south-1'
      MINIO_END_POINT = "{{ minio_ip_address }}"
      MINIO_PORT = 9000
      MINIO_ACCESS_KEY = "{{ minio_username }}"
      MINIO_SECRET_KEY = "{{ minio_password }}"
      MINIO_BUCKET = "{{ minio_bucket }}"
      AZURE_CONNECTION_STRING = "{{ azure_connection_string }}"
      AZURE_CONTAINER = "{{ azure_container }}"
      CONTAINER_FOLDER_NAME= 'process_input'
      ORACLE_BUCKET = "{{ oracle_bucket }}"
      KEY_CLOCK_URL = 'http://keycloak_app:8080/auth'
      REALM = 'cQube'
      KEY_CLOAK_CLIENT_ID = 'cqube-5.0'
      KEY_CLOAK_SECRET = 'd0b8122f-8dfb-46h7-b69a-f5cc4e25d000'
      KEY_CLOAK_ADMIN_CLIENT_ID = 'keycloak-admin'
      KEY_CLOAK_ADMIN_CLIENT_SECRET = '4c19653b-4047-4b19-819a-69315c491763'
      KEY_CLOAK_ADMIN_USERNAME = '{{ keycloak_adm_name }}'
      KEY_CLOAK_ADMIN_PASSWORD = '{{ keycloak_adm_password }}'
  when: mode_of_installation == "localhost"
  tags: [ install, update ]
