---
#- include_tasks: docker_container_sanity.yml
#  tags: install

- include_tasks: configure_base_dir.yml
  tags: [install, update ]

- include_tasks: configure_compose.yml
  tags: [install, update ]

- include_tasks: configure_program_selector.yml
  tags: [ install, update ]  

- include_tasks: configure_keycloak.yml
  tags: [ install, update ]

- include_tasks: configure_grafana.yml
  tags: [ install, update ]
