version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss
    container_name: monitoring_grafana
    restart: unless-stopped
    ports:
     - '3005:3005'
    environment:
      - "GF_SERVER_HTTP_PORT=3005"
    networks:
      cqube_net:
        ipv4_address: "10.0.0.15"
  prometheus:
    image: prom/prometheus
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
     - '9090:9090'
    networks:
      cqube_net:
        ipv4_address: "10.0.0.16"
  node_exporter:
    image: prom/node-exporter
    container_name: monitoring_nodeExporter
    restart: unless-stopped
    ports:
      - '9100:9100'
    networks:
      cqube_net:
        ipv4_address: "10.0.0.17"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: monitoring_cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - '9091:9091'
    command:
     - '-port=9091'
    networks:
      cqube_net:
        ipv4_address: "10.0.0.18"
networks:
  cqube_net:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: "10.0.0.0/24"
              gateway: "10.0.0.1"
    name: cqube_net
