- name: copying dockerfile script to ingestion repository
  template:
    src: Dockerfile.j2
    dest: "../microservices/ingestion-ms/Dockerfile"
    mode: "0644"  
  tags: [ install, update ]

- name: Loading required data inside .env file (public)
  template:
    src: public.env.j2
    dest: "../microservices/ingestion-ms/.env"
    mode: "0644"
  when: mode_of_installation != "localhost"
  tags: [ install, update ]


- name: Loading required data inside .env file (localhost)
  template:
    src: localhost.env.j2
    dest: "../microservices/ingestion-ms/.env"
    mode: "0644"
  when: mode_of_installation == "localhost"
  tags: [ install, update ]
